python_version = 'PY2'

py_binary(
    name = "alldeps",
    srcs = ["//:pomgen_files", "all_third_party_deps_pom.py"],
    main = "all_third_party_deps_pom.py",
    python_version = python_version,
)
