java_library(
    name = "lib",
    srcs = glob(["src/main/java/**/*.java"]),
    runtime_deps = ["@poppy_mvn//:org_apache_commons_commons_math3"],
    visibility = ["//examples/java/skip-artifact-generation/passthrough:__subpackages__"],
)    
