java_library(
    name = "fruit-api",
    srcs = glob(["src/main/java/**/*.java"]),
    deps = ["@poppy_antlr//:org_antlr_ST4",
            "@poppy_mvn//:com_google_guava_guava"],
    visibility = ["//visibility:public"],
)
