java_library(
    name = "lib2",
    srcs = glob(["src/main/java/**/*.java"]),
    runtime_deps = ["@maven//:org_apache_commons_commons_math3"],
    visibility = ["//examples/skip-artifact-generation/lib1_transitives:__subpackages__"],
)    
