java_library(
    name = "lib",
    srcs = glob(["src/main/java/**/*.java"]),
    runtime_deps = ["@org_apache_commons_commons_math3//jar"],
    visibility = ["//examples/skip-artifact-generation/passthrough:__subpackages__"],
)    
