java_library(
    name = "wintervegetables",
    srcs = glob(["src/main/java/**/*.java"]),
    deps = ["//example/healthyfoods/vegetable-api"],
    visibility = ["//example/juicer:__subpackages__"],
)
