"""
Copyright (c) 2018, salesforce.com, inc.
All rights reserved.
SPDX-License-Identifier: BSD-3-Clause
For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause
"""

import extdeps_pomgen
import os
import tempfile
import unittest

class ExtDepsPomgenTest(unittest.TestCase):

    def test1(self):
        self._setup_workspace()
        args = ("--repo_root", self.repo_root_path,)

        pom = extdeps_pomgen.main(args)

        self.assertIn("<groupId>com.google.guava</groupId>", pom)
        self.assertIn("<artifactId>guava</artifactId>", pom)
        self.assertIn("<version>23.0</version", pom)

    def _setup_workspace(self):
        self.repo_root_path = tempfile.mkdtemp("monorepo")
        self._add_WORKSPACE_file()
        self._add_maven_install_json_file()
        self._add_pom_template()
        self._write_file("","",".bazelversion", "1.2.1")

    def _add_WORKSPACE_file(self):
        content = """
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

RULES_JVM_EXTERNAL_TAG = "3.3"
RULES_JVM_EXTERNAL_SHA = "d85951a92c0908c80bd8551002d66cb23c3434409c814179c0ff026b53544dab"

http_archive(
    name = "rules_jvm_external",
    strip_prefix = "rules_jvm_external-%s" % RULES_JVM_EXTERNAL_TAG,
    sha256 = RULES_JVM_EXTERNAL_SHA,
    url = "https://github.com/bazelbuild/rules_jvm_external/archive/%s.zip" % RULES_JVM_EXTERNAL_TAG,
)

load("@rules_jvm_external//:defs.bzl", "maven_install")
load("@rules_jvm_external//:specs.bzl", "maven")

maven_install(
    name = 'maven',
    artifacts = [
        maven.artifact(group = 'com.google.guava', artifact = 'guava', version = '23.0', exclusions = ['*:*']),
    ],
    repositories = [
        'https://repo1.maven.org/maven2',
    ],
    version_conflict_policy = 'pinned',
    strict_visibility = True,
    generate_compat_repositories = True,
    resolve_timeout = 1800,
)
"""
        self._write_file("", "", "WORKSPACE", content)

    def _add_maven_install_json_file(self):
        content = """
{
    "dependency_tree": {
        "__AUTOGENERATED_FILE_DO_NOT_MODIFY_THIS_FILE_MANUALLY": -1063907353,
        "conflict_resolution": {},
        "dependencies": [
            {
                "coord": "com.google.guava:guava:23.0",
                "dependencies": [],
                "directDependencies": [],
                "exclusions": [
                    "*:*"
                ],
                "file": "v1/https/repo1.maven.org/maven2/com/google/guava/guava/23.0/guava-23.0.jar",
                "mirror_urls": [
                    "https://repo1.maven.org/maven2/com/google/guava/guava/23.0/guava-23.0.jar"
                ],
                "sha256": "7baa80df284117e5b945b19b98d367a85ea7b7801bd358ff657946c3bd1b6596",
                "url": "https://repo1.maven.org/maven2/com/google/guava/guava/23.0/guava-23.0.jar"
            },
            {
                "coord": "org.apache.commons:commons-lang3:3.9",
                "dependencies": [],
                "directDependencies": [],
                "exclusions": [
                    "*:*"
                ],
                "file": "v1/https/repo1.maven.org/maven2/org/apache/commons/commons-lang3/3.9/commons-lang3-3.9.jar",
                "mirror_urls": [
                    "https://repo1.maven.org/maven2/org/apache/commons/commons-lang3/3.9/commons-lang3-3.9.jar"
                ],
                "sha256": "de2e1dcdcf3ef917a8ce858661a06726a9a944f28e33ad7f9e08bea44dc3c230",
                "url": "https://repo1.maven.org/maven2/org/apache/commons/commons-lang3/3.9/commons-lang3-3.9.jar"
            },
            {
                "coord": "org.apache.commons:commons-math3:3.6.1",
                "dependencies": [],
                "directDependencies": [],
                "exclusions": [
                    "*:*"
                ],
                "file": "v1/https/repo1.maven.org/maven2/org/apache/commons/commons-math3/3.6.1/commons-math3-3.6.1.jar",
                "mirror_urls": [
                    "https://repo1.maven.org/maven2/org/apache/commons/commons-math3/3.6.1/commons-math3-3.6.1.jar"
                ],
                "sha256": "1e56d7b058d28b65abd256b8458e3885b674c1d588fa43cd7d1cbb9c7ef2b308",
                "url": "https://repo1.maven.org/maven2/org/apache/commons/commons-math3/3.6.1/commons-math3-3.6.1.jar"
            }
        ],
        "version": "0.1.0"
    }
}
        """
        self._write_file("", "", "maven_install.json", content)

    def _add_pom_template(self):
        content = "#{dependencies}"
        self._write_file("config", "", "pom_template.xml", content)

    def _write_file(self, package_rel_path, rel_path, filename, content):
        print(content)
        path = os.path.join(self.repo_root_path, package_rel_path, rel_path, 
                            filename)
        parent_dir = os.path.dirname(path)
        if not os.path.exists(parent_dir):
            os.makedirs(parent_dir)
        with open(path, "w") as f:
            f.write(content)

if __name__ == '__main__':
    unittest.main()
