load("@aspect_rules_py//py:defs.bzl", "py_venv")


py_venv(
    name = "venv",
    deps = [
        "//examples/python/111/computer/amiga/src/amiga:amiga_lib",
        "//examples/python/111/computer/amiga/src/amiga/workbench",
    ],
)

