java_library(
    name = "wintervegetables",
    srcs = glob(["src/main/java/**/*.java"]),
    deps = ["//examples/hello-world/healthyfoods/vegetable-api"],
    visibility = ["//examples/hello-world/juicer:__subpackages__"],
)
