java_library(
    name = "override_dep_test",
    deps = [
        # Commented the deps (Please see the Readme to read more)
        # "@javax//:javax_validation_validation_api",
        # "@org_apache//:org_apache_jclouds_jclouds_core",
    ]
)