load("@aspect_rules_py//py:defs.bzl", "py_library")


py_library(
    name = "workbench",
    srcs = ["workbench.py",],
    visibility = [
        "//examples/python/111/computer/amiga:__pkg__",
        "//examples/python/111/computer/amiga/src/amiga:__pkg__",
    ],
)
