load("@aspect_rules_py//py:defs.bzl", "py_library")


py_library(
    name = "message",
    srcs = ["message.py",],
    visibility = [
        "//examples/python/111/communicator/phone:__pkg__",
        "//examples/python/111/communicator/phone/src/phone:__pkg__",
    ],
)
