java_library(
    name = "coollib",
    srcs = glob(["src/main/java/**/*.java"]),
    deps = ["//examples/java/compile-only-dependencies/fancy",
            "@poppy_mvn//:com_google_guava_guava",
    ]
)

