java_library(
    name = "wintervegetables",
    srcs = glob(["src/main/java/**/*.java"]),
    deps = ["//examples/java/dependency-management/healthyfoods/vegetable-api",
            "@maven//:org_antlr_ST4"],
    visibility = ["//examples/java/dependency-management/juicer:__subpackages__"],
)
