name: ci
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: bazelbuild/setup-bazelisk@v2
      # - uses: actions/setup-python@v5
      #   with:
      #     python-version: '3.9'
      #     cache: 'pip' # caching pip dependencies
      - run: pip install --user lxml
      - run: bazel build //...
      - run: bazel test //...
